### PR TITLE
Match newline characters too

### PR DESCRIPTION
**Pull request by trevordixon**
Here's an example of a reply from Gmail:

'This is weird.\n\nOn Tue, Oct 2, 2012 at 1:18 PM, Image Description <\nsomeone@domain.com> wrote:\n\n> Here\'s the image to describe (click to enlarge):\n>\n>\n'

Sometimes there's a newline in the middle of the 'On …, … wrote:', and the dot (.) matches any character _except_ a newline. [\S\s] will match any character including the newline.

### CODE REVIEW

**Comment by pgherveou** [comment]
Hi Thanks for the pull-request but it does introduce a bug
if will break if you have the following text

```
On your mark
Ready
GO !
On Fri, May 25, 2012 at 1:33 PM test@test.com wrote:
xxx
```

**Comment by pgherveou** [comment]
I did add a test, I'll try to find a solution for this scenario, if you have one feel free to send another pull request

**Comment by trevordixon** [comment]
Good point. I should have run the tests. Sorry and thanks.

**Comment by pgherveou** [comment]
No pb I updated the tests in between it wasn't catching this scenario
Let me know if you find an easy solution

**Comment by pgherveou** [comment]
I updated the module it now truncate if a line contains "someone@domain.com"
Does this covers your example ? 
https://github.com/pgherveou/mailstrip/blob/master/src/test/tests.coffee#L35-43

**Comment by trevordixon** [comment]
Not quite. The issue is that sometimes the line like "On Tue, Oct 2, 2012 at 1:18 PM, Image Description wrote:" can sometimes have a newline. There should be a test that's something like this:

```
it 'after On ..., ...\n... wrote:', ->
    mailstrip(
      '''
      content

      On Tue, Oct 2, 2012 at 1:18 PM, Image Description
      <someone@domain.com> wrote:
      xxx
      '''
    ).should.equal 'content'
```

**Pull request merged**
